### ISSUE TITLE
手机上字体和ui问题

### ISSUE THREAD

**Issue by sunzhangchang** [Qsgs-Fans/FreeKill#280]
手机上字体过小以及ui边距过小。

**Comment by Notify-ctrl** [comment]
很多手游就是这个字体大小，我尽可能把字做得大了，还嫌小请用电脑玩

**Comment by sunzhangchang** [comment]
1.（我说的是按钮上的字体大小，不知道有没有被误解）很多手游是不是这个字体大小我不清楚，我只知道我玩的都没那么小，我感觉确实有点小了。我只是指出手机上字体小的问题，不是说我换成电脑玩就可以解决的。还有就是手机上的边距。

2. 很多手机屏幕都是圆角以及有摄像机孔的，这个ui会被遮住，这个问题您也没有提及。

 感觉freekill各方面都比无名杀要更好一点。我是希望freekill更完美的。还请您仔细看一下。如果您还是觉得没有问题，那么我也不打扰了。

**Comment by sunzhangchang** [comment]
不知道您是不是想先专注于游戏逻辑上的完善，如果是这样的话也没有问题。
