### ISSUE TITLE
希望加入牌局内音量控制功能

### ISSUE THREAD

**Issue by baisebaoma** [Qsgs-Fans/FreeKill#283]
我和朋友们第一次玩新月杀时，一开游戏许多朋友都被震聋了，而且无法单独调整音量。希望能够加入游戏内音量控制功能。

**Comment by shadlc** [comment]
1. 请随意进入一个单人模式或者服务器
2. 点击左上角自己的头像
3. 点击左下角音频选项
4. 此时有一个音效音量可以调节

希望能帮到你

**Comment by baisebaoma** [comment]
> 1. 请随意进入一个单人模式或者服务器
> 2. 点击左上角自己的头像
> 3. 点击左下角音频选项
> 4. 此时有一个音效音量可以调节
> 
> 希望能帮到你

您好，感谢回复！不好意思我的表述有误，我指的是**牌局内**调整音量按钮。感谢！

**Comment by Mechanel** [comment]
已完成，新版本将装载此功能
