### ISSUE TITLE
exppattern.lua 文档错误

### ISSUE THREAD

**Issue by baisebaoma** [Qsgs-Fans/FreeKill#300]
您好，

一个文档里的小问题，[exppattern.lua](https://github.com/Qsgs-Fans/FreeKill/blob/master/lua/core/exppattern.lua) 中，中文和下面给的例子的花色和点数反过来了。

> 其中 Matcher 的格式为 牌名|花色|点数|位置|详细牌名|类型|牌的id
>   更进一步，“点数” 可以用 '~' 符号表示数字的范围，并且可以用 AJQK 表示对应点数
> 
>   例如：
>   slash,jink|2~4|spade;.|.|.|.|.|trick

经实验，文档中中文给的“牌名|花色|点数”是不正确的，无法匹配到，而例子给的"slash,jink|2~4|spade"（即“牌名|点数|花色”）是可以匹配到的。

希望能对您有所帮助。感谢！

**Comment by Notify-ctrl** [comment]
感谢指出，如果您能提一个修复pr就更好了😃
