### ISSUE TITLE
[Room/Error Occured] v0.4.3 单人游戏下 无限循环报错

### ISSUE THREAD

**Issue by Sorrow-Scarlet** [Qsgs-Fans/FreeKill#306]
![image](https://github.com/Qsgs-Fans/FreeKill/assets/61646954/a4a5d50b-17e5-4d1d-858a-38179aedaf11)

如上图所示，贾充喝了个jiu酒，然后就报错了（

01/13 17:54:39 Room[C] D:\FreeKill-release\packages/tenyear/tenyear_ex.lua:3429: attempt to index a nil value (local 'card')
stack traceback:
        D:\FreeKill-release\packages/tenyear/tenyear_ex.lua:3429: in method 'prohibitUse'
        D:\FreeKill-release\lua\core\player.lua:894: in method 'prohibitUse'
        D:\FreeKill-release\lua\server\ai\random_ai.lua:18: in field 'useActiveSkill'
        D:\FreeKill-release\lua\server\ai\random_ai.lua:215: in field '?'
        D:\FreeKill-release\lua\server\ai\ai.lua:38: in method 'makeReply'
        D:\FreeKill-release\lua\server\serverplayer.lua:122: in upvalue '_waitForReply'
        D:\FreeKill-release\lua\server\serverplayer.lua:164: in method 'waitForReply'
        D:\FreeKill-release\lua\server\room.lua:722: in method 'doRequest'
        lua/server/events/gameflow.lua:321: in function <lua/server/events/gameflow.lua:316>
        (...tail calls...)
        lua/server/events/gameflow.lua:276: in function <lua/s[mp3float @ 00000188ff55d1c0] erver/events/gameflowCould not update timestamps for skipped samples.
.lua:267>
        (...tail calls...)
01/13 17:54:39 Room[C] D:\FreeKill-release\packages/tenyear/tenyear_ex.lua:3429: attempt to index a nil value (local 'card')
stack traceback:
        D:\FreeKill-release\packages/tenyear/tenyear_ex.lua:3429: in method 'prohibitUse'
        D:\FreeKill-release\lua\core\player.lua:894: in method 'prohibitUse'
        D:\FreeKill-release\lua\server\ai\random_ai.lua:18: in field 'useActiveSkill'
        D:\FreeKill-release\lua\server\ai\random_ai.lua:215: in field '?'
        D:\FreeKill-release\lua\server\ai\ai.lua:38: in method 'makeReply'
        D:\FreeKill-release\lua\server\serverplayer.lua:122: in upvalue '_waitForReply'
        D:\FreeKill-release\lua\server\serverplayer.lua:164: in method 'waitForReply'
        D:\FreeKill-release\lua\server\room.lua:722: in method 'doRequest'
        D:\FreeKill-release\lua\server\room.lua:1672: in method 'askForChoice'
        D:\FreeKill-release\packages/overseas/overseas_sp.lua:550: in method 'cost'
        D:\FreeKill-release\lua\core\skill_type\trigger.lua:60: in function <D:\FreeKill-release\lua\core\skill_type\trigger.lua:58>
        (...tail calls...)
        D:\FreeKill-release\lua\server\gamelogic.lua:390: in method 'trigger'
        lua/server/events/gameflow.lua:362: in method 'clear_func'
        lua/server/events/misc.lua:131: in function <lua/server/events/misc.lua:128>
        (...tail calls...)
01/13 17:54:39 Room[C] cannot resume dead coroutine
stack traceback:
01/13 17:54:39 Room[C] cannot resume dead coroutine
stack traceback:
01/13 17:54:39 Room[C] cannot resume dead coroutine
stack traceback:
01/13 17:54:39 Room[C] cannot resume dead coroutine
stack traceback:
01/13 17:54:39 Room[C] cannot resume dead coroutine
stack traceback:
01/13 17:54:39 Room[C] cannot resume dead coroutine
stack traceback:
01/13 17:54:39 Room[C] cannot resume dead coroutine
stack traceback:
01/13 [mp3float @ 00000188ff55c5c0] 17:54:39 Could not update timestamps for discarded samples.
Room[C] cannot resume dead coroutine
stack traceback:
01/13 17:54:39 Room[C] cannot resume dead coroutine
stack traceback:
01/13 17:54:39 Room[C] cannot resume dead coroutine
stack traceback:
01/13 17:54:39 Room[C] cannot resume dead coroutine
stack traceback:
01/13 17:54:39 Room[C] cannot resume dead coroutine
stack traceback:
01/13 17:54:39 Room[C] cannot resume dead coroutine
stack traceback:
01/13 17:54:39 Room[C] cannot resume dead coroutine
stack traceback:
01/13 17:54:39 Room[C] cannot resume dead coroutine
stack traceback:
01/13 17:54:39 Room[C] cannot resume dead coroutine
stack traceback:
01/13 17:54:39 Room[C] cannot resume dead coroutine
stack traceback:
01/13 17:54:39 Room[C] cannot resume dead coroutine
stack traceback:
01/13 17:54:39 Room[C] cannot resume dead coroutine
stack traceback:
01/13 17:54:39 Room[C] cannot resume dead coroutine
stack traceback:
01/13 17:54:39 Room[C] cannot resume dead coroutine
stack traceback:
01/13 17:54:39 Room[C] cannot resume dead coroutine
stack traceback:
01/13 17:54:39 Room[C] cannot resume dead coroutine
stack traceback:
01/13 17:54:39 Room[C] cannot resume dead coroutine
stack traceback:
01/13 17:54:39 Room[C] cannot resume dead coroutine
stack traceback:
01/13 17:54:39 Room[C] cannot resume dead coroutine
stack traceback:
01/13 17:54:39 Room[C] cannot resume dead coroutine
stack traceback:
01/13 17:54:39 Room[C] cannot resume dead coroutine
stack traceback:
01/13 17:54:39 Room[C] cannot resume dead coroutine
stack traceback:
01/13 17:54:39 Room[C] cannot resume dead coroutine
stack traceback:
01/13 17:54:39 Room[C] cannot resume dead coroutine
stack traceback:
01/13 17:54:39 Room[C] cannot resume dead coroutine
stack traceback:
01/13 17:54:39 Room[C] cannot resume dead coroutine
stack traceback:
01/13 17:54:39 Room[C] cannot resume dead coroutine
stack traceback:
01/13 17:54:39 Room[C] cannot resume dead coroutine
stack traceback:
01/13 17:54:39 Room[C] cannot resume dead coroutine
stack traceback:
01/13 17:54:39 Room[C] cannot resume dead coroutine
stack traceback:
01/13 17:54:39 Room[C] cannot resume dead coroutine
stack traceback:
01/[mp3float @ 00000188ff55a5c0] 13 Could not update timestamps for discarded samples.
17:54:39 Room[C] cannot resume dead coroutine
stack traceback:
01/13 17:54:39 Room[C] cannot resume dead coroutine
stack traceback:
01/13 17:54:39 Room[C] cannot resume dead coroutine
stack traceback:
01/13 17:54:39 Room[C] cannot resume dead coroutine
stack traceback:
01/13 17:54:39 Room[C] cannot resume dead coroutine
stack traceback:
01/13 17:54:39 Room[C] cannot resume dead coroutine
stack traceback:
01/13 17:54:39 Room[C] cannot resume dead coroutine
stack traceback:
01/13 17:54:40 Room[C] cannot resume dead coroutine
stack traceback:
01/13 17:54:40 Room[C] cannot resume dead coroutine
stack traceback:
01/13 17:54:40 Room[C] cannot resume dead coroutine
stack traceback:
01/13 17:54:40 Room[C] cannot resume dead coroutine
stack traceback:
01/13 17:54:40 Room[C] cannot resume dead coroutine
stack traceback:
01/13 17:54:40 Room[C] cannot resume dead coroutine
stack traceback:
01/13 17:54:40 Room[C] cannot resume dead coroutine
stack traceback:
01/13 17:54:40 Room[C] cannot resume dead coroutine
stack traceback:
01/13 17:54:40 Room[C] cannot resume dead coroutine
stack traceback:
01/13 17:54:40 Room[C] cannot resume dead coroutine
stack traceback:
01/13 17:54:40 Room[C] cannot resume dead coroutine
stack traceback:
01/13 17:54:40 Room[C] cannot resume dead coroutine
stack traceback:
01/13 17:54:40 Room[C] cannot resume dead coroutine
stack traceback:
01/13 17:54:40 Room[C] cannot resume dead coroutine
stack traceback:
0[mp3float @ 00000188ff55d1c0] 1/1Could not update timestamps for discarded samples.
3 17:54:40 Room[C] cannot resume dead coroutine
stack traceback:
01/13 17:54:40 Room[C] cannot resume dead coroutine
stack traceback:
01/13 17:54:40 Room[C] cannot resume dead coroutine
stack traceback:
01/13 17:54:40 Room[C] cannot resume dead coroutine
stack traceback:
01/13 17:54:40 Room[C] cannot resume dead coroutine
stack traceback:
01/13 17:54:40 Room[C] cannot resume dead coroutine
stack traceback:
01/13 17:54:40 Room[C] cannot resume dead coroutine
stack traceback:
01/13 17:54:40 Room[C] cannot resume dead coroutine
stack traceback:
01/13 17:54:40 Room[C] cannot resume dead coroutine
stack traceback:
01/13 17:54:40 Room[C] cannot resume dead coroutine
stack traceback:
01/13 17:54:40 Room[C] cannot resume dead coroutine
stack traceback:
01/13 17:54:40 Room[C] cannot resume dead coroutine
stack traceback:
01/13 17:54:40 Room[C] cannot resume dead coroutine
stack traceback:
01/13 17:54:40 Room[C] cannot resume dead coroutine
stack traceback:
01/13 17:54:40 Room[C] cannot resume dead coroutine
stack traceback:
01/13 17:54:40 Room[C] cannot resume dead coroutine
stack traceback:
01/13 17:54:40 Room[C] cannot resume dead coroutine
stack traceback:
01/13 17:54:40 Room[C] cannot resume dead coroutine
stack traceback:
01/13 17:54:40 Room[C] cannot resume dead coroutine
stack traceback:
01/13 17:54:40 Room[C] cannot resume dead coroutine
stack traceback:
01/13 17:54:40 Room[C] cannot resume dead coroutine
stack traceback:
01/13 17:54:40 Room[C] cannot resume dead coroutine
stack traceback:
01/13 17:54:40 Room[C] cannot resume dead coroutine
stack traceback:
01/13 17:54:40 Room[C] cannot resume dead coroutine
stack traceback:
01/13 17:54:40 Room[C] cannot resume dead coroutine
stack traceback:
01/13 17:54:40 Room[C] cannot resume dead coroutine
stack traceback:
01/13 17:54:40 Room[C] cannot resume dead coroutine
stack traceback:
01/13 17:54:40 Room[C] cannot resume dead coroutine
stack traceback:
01/13 17:54:40 Room[C] cannot resume dead coroutine
stack traceback:
01[mp3 @ 00000188ee0ac900] /13 Estimating duration from bitrate, this may be inaccurate
17:54:40 Room[C] cannot resume dead coroutine
stack traceback:
01/13 17:54:40 Room[C] cannot resume dead coroutine
stack traceback:
01/13 17:54:40 Room[C] cannot resume dead coroutine
stack traceback:
01/13 17:54:40 Room[C] cannot resume dead coroutine
stack traceback:
01/13 17:54:40 Room[C] cannot resume dead coroutine
stack traceback:
01/13 17:54:40 Room[C] cannot resume dead coroutine
stack traceback:
01/13 17:54:40 Room[C] cannot resume dead coroutine
stack traceback:
01/13 17:54:40 Room[C] cannot resume dead coroutine
stack traceback:
01/13 17:54:40 Room[C] cannot resume dead coroutine
stack traceback:
01/13 17:54:40 Room[C] cannot resume dead coroutine
stack traceback:
01/13 17:54:40 Room[C] cannot resume dead coroutine
stack traceback:
01/13 17:54:40 Room[C] cannot resume dead coroutine
stack traceback:
01/13 17:54:40 Room[C] cannot resume dead coroutine
stack traceback:
01/13 17:54:40 Room[C] cannot resume dead coroutine
stack traceback:
01/13 17:54:40 Room[C] cannot resume dead coroutine
stack traceback:
01/13 17:54:40 Room[C] cannot resume dead coroutine
stack traceback:
01/13 17:54:40 Room[C] cannot resume dead coroutine
stack traceback:
01/13 17:54:40 Room[C] cannot resume dead coroutine
stack traceback:
01/13 17:54:40 Room[C] cannot resume dead coroutine
stack traceback:
01/13 17:54:40 Room[C] cannot resume dead coroutine
stack traceback:
01/13 17:54:40 Room[C] cannot resume dead coroutine
stack traceback:
01/13 17:54:40 Room[C] cannot resume dead coroutine
stack traceback:
01/13 17:54:40 Room[C] cannot resume dead coroutine
stack traceback:
01/13 17:54:40 Room[C] cannot resume dead coroutine
stack traceback:
01/13 17:54:40 Room[C] cannot resume dead coroutine
stack traceback:
01/13 17:54:40 Room[C] cannot resume dead coroutine
stack traceback:
01/13 17:54:40 Room[C] cannot resume dead coroutine
stack traceback:
01/13 17:54:40 Room[C] cannot resume dead coroutine
stack traceback:
01/13 17:54:40 Room[C] cannot resume dead coroutine
stack traceback:
01/13 17:54:40 Room[C] cannot resume dead coroutine
stack traceback:
01/13 17:54:40 Room[C] cannot resume dead coroutine
stack traceback:
01/13 17:54:40 Room[C] cannot resume dead coroutine
stack traceback:
01/13 17:54:40 Room[C] cannot resume dead coroutine
stack traceback:
01/13 17:54:40 Room[C] cannot resume dead coroutine
stack traceback:
01/13 17:54:40 Room[C] cannot resume dead coroutine
stack traceback:
01/13 17:54:40 Room[C] cannot resume dead coroutine
stack traceback:
01/13 17:54:40 Room[C] cannot resume dead coroutine
stack traceback:
01/13 17:54:40 Room[C] cannot resume dead coroutine
stack traceback:
01/13 17:54:40 Room[C] cannot resume dead coroutine
stack traceback:
01/13 17:54:40 Room[C] cannot resume dead coroutine
stack traceback:
01/13 17:54:40 Room[C] cannot resume dead coroutine
stack traceback:
01/13 17:54:40 Room[C] cannot resume dead coroutine
stack traceback:
01/13 17:54:40 Room[C] cannot resume dead coroutine
stack traceback:
01/13 17:54:40 Room[C] cannot resume dead coroutine
stack traceback:
01/13 17:54:40 Room[C] cannot resume dead coroutine
stack traceback:
01/13 17:54:40 Room[C] cannot resume dead coroutine
stack traceback:
01/13 17:54:40 Room[C] cannot resume dead coroutine
stack traceback:
01/13 17:54:40 Room[C] cannot resume dead coroutine
stack traceback:
01/13 17:54:40 Room[C] cannot resume dead coroutine
stack traceback:
01/13 17:54:40 Room[C] cannot resume dead coroutine
stack traceback:
01/13 17:54:40 Room[C] cannot resume dead coroutine
stack traceback:
01/13 17:54:40 Room[C] cannot resume dead coroutine
stack traceback:
01/13 17:54:40 Room[C] cannot resume dead coroutine
stack traceback:
01/13 17:54:40 Room[C] cannot resume dead coroutine
stack traceback:
01/13 17:54:40 Room[C] cannot resume dead coroutine
stack traceback:
01/13 17:54:40 Room[C] cannot resume dead coroutine
stack traceback:
01/13 17:54:40 Room[C] cannot resume dead coroutine
stack traceback:
01/13 17:54:40 Room[C] cannot resume dead coroutine
stack traceback:
01/13 17:54:40 Room[C] cannot resume dead coroutine
stack traceback:
01/13 17:54:40 Room[C] cannot resume dead coroutine
stack traceback:
01/13 17:54:40 Room[C] cannot resume dead coroutine
stack traceback:
01/13 17:54:40 Room[C] cannot resume dead coroutine
stack traceback:
01/13 17:54:40 Room[C] cannot resume dead coroutine
stack traceback:
01/13 17:54:40 Room[C] cannot resume dead coroutine
stack traceback:
01/13 17:54:40 Room[C] cannot resume dead coroutine
stack traceback:
01/13 17:54:40 Room[C] cannot resume dead coroutine
stack traceback:
01/13 17:54:40 Room[C] cannot resume dead coroutine
stack traceback:
01/13 17:54:40 Room[C] cannot resume dead coroutine
stack traceback:
01/13 17:54:40 Room[C] cannot resume dead coroutine
stack traceback:
01/13 17:54:40 Room[C] cannot resume dead coroutine
stack traceback:
01/13 17:54:40 Room[C] cannot resume dead coroutine
stack traceback:
01/13 17:54:40 Room[C] cannot resume dead coroutine
stack traceback:
01/13 17:54:40 Room[C] cannot resume dead coroutine
stack traceback:
01/13 17:54:40 Room[C] cannot resume dead coroutine
stack traceback:
01/13 17:54:40 Room[C] cannot resume dead coroutine
stack traceback:
01/13 17:54:40 Room[C] cannot resume dead coroutine
stack traceback:
01/13 17:54:40 Room[C] cannot resume dead coroutine
stack traceback:
01/13 17:54:40 Room[C] cannot resume dead coroutine
stack traceback:
01/13 17:54:40 Room[C] cannot resume dead coroutine
stack traceback:
01/13 17:54:40 Room[C] cannot resume dead coroutine
stack traceback:
01/13 17:54:40 Room[C] cannot resume dead coroutine
stack traceback:
01/13 17:54:40 Room[C] cannot resume dead coroutine
stack traceback:
01/13 17:54:40 Room[C] cannot resume dead coroutine
stack traceback:
01/13 17:54:40 Room[C] cannot resume dead coroutine
stack traceback:
01/13 17:54:40 Room[C] cannot resume dead coroutine
stack traceback:
01/13 17:54:40 Room[C] cannot resume dead coroutine
stack traceback:
01/13 17:54:40 Room[C] cannot resume dead coroutine
stack traceback:
01/13 17:54:40 Room[C] cannot resume dead coroutine
stack traceback:
01/13 17:54:40 Room[C] cannot resume dead coroutine
stack traceback:
01/13 17:54:40 Room[C] cannot resume dead coroutine
stack traceback:
01/13 17:54:40 Room[C] cannot resume dead coroutine
stack traceback:
01/13 17:54:40 Room[C] cannot resume dead coroutine
stack traceback:
01/13 17:54:40 Room[C] cannot resume dead coroutine
stack traceback:
01/13 17:54:40 Room[C] cannot resume dead coroutine
stack traceback:
01/13 17:54:40 Room[C] cannot resume dead coroutine
stack traceback:
01/13 17:54:40 Room[C] cannot resume dead coroutine
stack traceback:
01/13 17:54:40 Room[C] cannot resume dead coroutine
stack traceback:

**Comment by Notify-ctrl** [comment]
0.4.4已经修复
