### ISSUE TITLE
国内手机装编译好的apk报毒。。

### ISSUE THREAD

**Issue by cwateryuan** [Qsgs-Fans/FreeKill#310]
非常感谢作者哈。就想搞个服务器自己朋友娱乐玩。
这个能帮忙解决下吗~~
![Screenshot_2024-01-27-21-02-56-373_com miui packa](https://github.com/Qsgs-Fans/FreeKill/assets/26851098/ca979716-2015-4a4e-a520-0b096806532c)

**Comment by Notify-ctrl** [comment]
无视报毒就行了，怎么可能有毒。。。但确实没备案
