### ISSUE TITLE
如何切换语言？

### ISSUE THREAD

**Issue by akzhol0921** [Qsgs-Fans/FreeKill#330]
如题，游戏内无切换语言的按钮，外部 config 改了无效

**Comment by Notify-ctrl** [comment]
进入大厅后点击左上角自己的头像，第二个Tab页里面有语言切换下拉框。目前支持中文和英文。

**Comment by Notify-ctrl** [comment]
顺便欢迎加入Discord群组一起讨论： https://discord.gg/tp35GrQR6v
