### ISSUE TITLE
安卓版会有白边

小米14 澎湃os开发版
屏幕上一直会显示一个细细的白边
因为是圆角屏幕 就更明显了
好像是游戏窗口化了一样

### ISSUE THREAD

**Issue by Sev73n** [Qsgs-Fans/FreeKill#346]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Notify-ctrl** [comment]
Qt quick的问题，无力呀
