### ISSUE TITLE
关于新月杀联机模式添加电脑

### ISSUE THREAD

**Issue by 3069740541** [Qsgs-Fans/FreeKill#354]
**Is your feature request related to a problem? Please describe.**
新月杀联机模式无法添加电脑
**Describe the solution you'd like**
添加电脑处为黑色，无法点击（身份模式）
**Describe alternatives you've considered**
如果可以的话，增加添加电脑的功能
**Additional context**

**Comment by 3069740541** [comment]
补充：添加机器人（电脑）无法添加

**Comment by Mechanel** [comment]
新月杀提供了服务器开启或关闭机器人的选项，目前主服不支持添加机器人
