### ISSUE TITLE
小米平板 4 MIUI10 打开最新版新月杀直接闪退

### ISSUE THREAD

**Issue by QVQSmile** [Qsgs-Fans/FreeKill#364]
**Describe the bug**
小米平板 4 打开最新版新月杀直接闪退，使用 虚拟框架打开也失败

**To Reproduce**
1. 安装最新版新月杀 apk
2. 点击打开新月杀，黑屏后闪退

**Desktop (please complete the following information):**
 - OS: [MIUI 10.3.2 稳定版/Android 8.1.0]
 - Version [游戏版本 0.4.1.9]

**Smartphone (please complete the following information):**
 - Device: [e.g.  小米平板 4 4+64G]
 - OS: [MIUI 10.3.2]

**Additional context**
会不会是系统版本太老旧，需要升级新版本的安卓。具体是要升级到多少？小米平板 4 能不能通过刷机实现？

**Comment by Notify-ctrl** [comment]
安卓10至少
