### ISSUE TITLE
-1: 双端牌堆信息同步

### ISSUE THREAD

**Issue by Notify-ctrl** [Qsgs-Fans/FreeKill#374]
如题，断线或者旁观时，额外将牌堆信息发送至客户端

**Comment by YoumuKon** [comment]
> 断线

应为`断线重连时`，笼统来说，只要是进入一个正在对局的房间里就要发送牌堆信息（包括录像）

**Comment by YoumuKon** [comment]
录像本质也是进入房间
还有一种录像是“旁观时保存录像”，这种录像的开头就是旁观进入已有对局的房间

**Comment by Notify-ctrl** [comment]
> 录像本质也是进入房间 还有一种录像是“旁观时保存录像”，这种录像的开头就是旁观进入已有对局的房间

那你就错了 录像没有进入房间 玩家其实还在大厅 完全就是把收到的数据再现一遍而已

**Comment by Notify-ctrl** [comment]
Qsgs-Fans/freekill-core@1002a93cb95645cda298a8d348ba2955bab05280 这里已经用新的函数表达了断线和重连时应传输的值；还没实际做客户端里面重连的逻辑，不过这套数据应该就能满足时刻同步牌堆信息吧？

**Comment by Notify-ctrl** [comment]
Qsgs-Fans/freekill-core@e09207b9e63ef867f35630be269d3c6431c934dd 已完成！
