### ISSUE TITLE
使用新API重写所有Request，并自定义timeout

### ISSUE THREAD

**Issue by Notify-ctrl** [Qsgs-Fans/FreeKill#379]
如题，但是这个依赖于 #377 

就假设#377做完了，那么下一步就是把这些request全改了，全改的同时

> 选将、观星、严教等交互烧条时间延长

把这个上古todo想办法解决。

**Comment by YoumuKon** [comment]
这个可以让request自己指定一个timeout

**Comment by Notify-ctrl** [comment]
> 这个可以让request自己指定一个timeout

接口呀，关键是接口，request本来就能自己指定timeout

**Comment by YoumuKon** [comment]
> 接口呀，关键是接口

问题关键肯定是接口，再细究的话——谁使用这个接口？谁接受这个接口？接口要传输什么？
