### ISSUE TITLE
删除ChangeSelf

### ISSUE THREAD

**Issue by Notify-ctrl** [Qsgs-Fans/FreeKill#380]
已经不存在未知牌了，changeSelf也不需要了，让客户端知道自己正在控制哪些角色就可以了。

具体重构方案仍需探讨

**Comment by Notify-ctrl** [comment]
想要做这个首先梳理一下目前这个changeSelf的原理以及存在的理由。

- 一控多时，会有切换到其他视角的需求。
- 切换之前，服务端发送StartChangeSelf给控制者。
- 控制者暂停处理接下来的所有消息，向服务端发送changeself消息
- 服务端进入异步后处理changeself，将手牌信息发回
- 客户端开始ChangeSelf，切换视角，然后处理接下来收到的消息

这么复杂的流程说到底是-1导致的。-1没了，那么就能把流程简单化不少。比如：

- 服务端发送ChangeSelf
- 控制着立刻切换视角，处理剩余信息

不过，当一名控制者需要同时处理多个询问时怎么办呢？比如求无懈，或者同时选将之类的？

**Comment by Notify-ctrl** [comment]
为此，我的看法是：弄不了，就按原版那样点取消后若request继续中的话那就切视角，想办法修一下这个，毕竟服务端还是有必要维护每个Player对应的_observer的

**Comment by YoumuKon** [comment]
> 这么复杂的流程说到底是-1导致的。-1没了，那么就能把流程简单化不少
不仅是因为-1，包括标记、锁视、可见性之类的客户端元素也要纳入考虑的一环

> 不过，当一名控制者需要同时处理多个询问时怎么办呢？比如求无懈，或者同时选将之类的？
这个没办法，毕竟客户端只有一个DashBoard……理论上也只能操控一个玩家……
