### ISSUE TITLE
多系统支持记录

### ISSUE THREAD

**Issue by YoumuKon** [Qsgs-Fans/FreeKill#395]
- [X] Windows
- [X] 安卓
- [X] MacOS (#365)
- [ ] IOS
- [ ] 鸿蒙

暂且做个记录

**Comment by Notify-ctrl** [comment]
我们Linux用户怎么你了😠

**Comment by Notify-ctrl** [comment]
这个在README里面提一下就行了吧，没必要创个milestone（基本各个平台就是改改CMakeLists.txt），这个issue你看着关关

**Comment by acg7878** [comment]
能否支持iOS呢
