### ISSUE TITLE
Linux端编译后运行会崩溃

### ISSUE THREAD

**Issue by acg7878** [Qsgs-Fans/FreeKill#410]
我使用的是archlinux，aur版本停留在19,我下了最新源码进行cmake编译，但是似乎运行会崩溃

**Comment by acg7878** [comment]
sorry我是个菜鸟，把游戏文件拖到build目录就好了。。。。

**Comment by acg7878** [comment]
![c4a1f4ab534957d7bcf7bd5846e31401](https://github.com/user-attachments/assets/4c8dc56f-4f1e-4d8b-9d5a-0e4dfc80a557)
在登陆的时候会闪退

**Comment by acg7878** [comment]
是我编译的问题吗，我git clone后在build文件夹编译，将得到的FreeKill可执行文件拷贝到项目根目录

**Comment by Notify-ctrl** [comment]
算了0.4.23再更新aur 目前还有点小bug
