### ISSUE TITLE
关于添加自定义玩法的提议和求助

### ISSUE THREAD

**Issue by Hys656-5** [Qsgs-Fans/FreeKill#416]
如在添加房间内时，针对各个身份的强化，如八人军争中对主公添加强化可以每回合多摸牌，额外自定义主公技能，，
求助：
顺便求助下开发玩法拓展包攻略，
我想开发一个模式的拓展包，应该怎么规范导入到私服

**Comment by Notify-ctrl** [comment]
第一段不予置评，后面的可以看gamemode包里面怎么写模式的 https://gitee.com/Qsgs-Fans/gamemode
